### ISSUE TITLE
Find out why one of the electron executables does not work in OSX

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#426]
## Problem Definition

When downloading the OSX bundle there are two executable files. One works but the other, the one with the electron logo, fails. This leads to confusion for most first-time OSX users.

Check our readme [here](https://rotkehlchen.readthedocs.io/en/latest/installation_guide.html#osx) for more details.

## Task

Find out why this happens. It has something to do with our app not being an "approved" app in MacOSX and getting hit by [translocation](https://lapcatsoftware.com/articles/app-translocation.html).

If possible fix it.

## Related issues

Related old issue: https://github.com/rotkehlchenio/rotkehlchen/issues/339
Related issue on OSX packaging: https://github.com/rotkehlchenio/rotkehlchen/issues/26

**Comment by LefterisJP** [comment]
Finally some more information. So what happens is that the first time Rotkehlchen is opened through the electron app icon then the python backend process crashes at the start with the following:
```
stuff
Before guess packaged
Calling python backend with: /Users/johndoe/w/rotkehlchen/rotkehlchen-darwin-x64-v0.6.1.dev577+g3572c83.d20190828/rotkehlchen.app/Contents/Resources/app/rotkehlchen_py_dist/rotkehlchen-0.6.1.dev577+g3572c83.d20190828-macos --zerorpc-port 4242
child process success on port 4242
CREATED PYPROCESS
Failed to start rotkehlchen backend:
Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 14, in main
  File "rotkehlchen/server.py", line 46, in __init__
  File "rotkehlchen/rotkehlchen.py", line 100, in __init__
  File "logging/__init__.py", line 1900, in basicConfig
  File "logging/__init__.py", line 1092, in __init__
  File "logging/__init__.py", line 1121, in _open
PermissionError: [Errno 13] Permission denied: '/rotkehlchen.log'


python subprocess killed with signal null and code 3
KILLING PYPROCESS

```
