### ISSUE TITLE
Python server does not start correctly after installation

### ISSUE THREAD

**Issue by Arachnid** [rotkehlchenio/rotkehlchen#5]
After following the installation instructions from the README, and running `npm start`, I get the following error:

```
$ npm start

> rotkehlchen@ start /Users/nickjohnson/Downloads/rotkehlchen
> electron .

At not packaged: script:/Users/nickjohnson/Downloads/rotkehlchen/rotkelchen/server.py port: 4242
child process success on port 4242
CREATED PYPROCESS
python subprocess killed with signal null and code 1
```

Running `python -m rotkehlchen` gives the following error:

```
$ python -m rotkelchen
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/nickjohnson/Downloads/rotkehlchen/rotkelchen/__main__.py", line 23, in <module>
    main()
  File "/Users/nickjohnson/Downloads/rotkehlchen/rotkelchen/__main__.py", line 10, in main
    from rotkelchen.server import RotkelchenServer
  File "/Users/nickjohnson/.virtualenvs/rotkelchen/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "rotkelchen/rotkelchen.py", line 7, in <module>
    from rotkelchen.utils import (
  File "/Users/nickjohnson/.virtualenvs/rotkelchen/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named utils
```

**Comment by LefterisJP** [comment]
Hey Nick!

I see you are trying to use Python 2.7. Try with latest python 3. Rotkehlchen only supports python 3.

**Comment by chevdor** [comment]
Same issue here, similar but not identical output.

```
$ python -m rotkelchen
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/rotkehlchen/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/envs/rotkehlchen/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/will/projects/rotkehlchen/rotkelchen/__main__.py", line 23, in <module>
    main()
  File "/Users/will/projects/rotkehlchen/rotkelchen/__main__.py", line 10, in main
    from rotkelchen.server import RotkelchenServer
  File "/Users/will/projects/rotkehlchen/rotkelchen/server.py", line 15, in <module>
    from rotkelchen.rotkelchen import Rotkelchen
  File "/Users/will/projects/rotkehlchen/rotkelchen/rotkelchen.py", line 20, in <module>
    from rotkelchen.data_handler import DataHandler
  File "/Users/will/projects/rotkehlchen/rotkelchen/data_handler.py", line 20, in <module>
    from rotkelchen.dbhandler import DBHandler
  File "/Users/will/projects/rotkehlchen/rotkelchen/dbhandler.py", line 6, in <module>
    from pysqlcipher3 import dbapi2 as sqlcipher
ModuleNotFoundError: No module named 'pysqlcipher3'
```
I am using python 3.6.4

**Comment by Arachnid** [comment]
@LefterisJP Oops, I missed that, sorry.

**Comment by LefterisJP** [comment]
@Arachnid Tell me if it works after that.

@chevdor I see this is OSX. Unfortunately rotkehlchen at the moment only supports Linux. I have only tried it in 2 different Linux distros. Eventually OSX and Windows will be supported but need to find the time or someone to help me do it.

Seems that for some reason pysqlcipher3 was not properly installed. Have you manage to install sqlcipher in OSX? Pysqlcipher depends on this system package.

**Comment by chevdor** [comment]
I realize that the issue I am running into has probably nothing to do with the one Nick initially ran into. I don´t want to highjack this issue and will open another one more OSX related.

**Comment by LefterisJP** [comment]
@Arachnid hey Nick is this still an issue?
