### ISSUE TITLE
Running from source on OSX doesn't prompt for login

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#65]
I made it all the way through npm start without errors. Electron started with no errors. Nothing happens, how do I login or signup?

**Comment by kascheri12** [comment]
Hi @LefterisJP 

You got it, there's an error in the console:
```
Uncaught Error: The module '~/rotkehlchen/node_modules/zmq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (~/rotkehlchen/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (~/rotkehlchen/node_modules/zmq/lib/index.js:6:30)
```

**Comment by kascheri12** [comment]
Nothing abnormal in `~/rotkelhchen/rotkelhchen.log`
```
24/05/2018 21:53:47 PDT -- DEBUG:rotkehlchen.rotkehlchen:Main loop start
24/05/2018 21:53:47 PDT -- DEBUG:rotkehlchen.rotkehlchen:Maybe upload to server
24/05/2018 21:53:47 PDT -- DEBUG:rotkehlchen.rotkehlchen:Main loop end
24/05/2018 21:54:22 PDT -- DEBUG:rotkehlchen.server:Shutdown initiated
```

**Comment by LefterisJP** [comment]
Argh not this again. Can you try to clean npm modules and reinstall but add an electron rebuild step at the end, just like the package [`setup.sh`](https://github.com/rotkehlchenio/rotkehlchen/blob/master/setup.sh#L13) does?

So basically:

```
# clean caches, very important!!!!!
rm -rf ~/.node-gyp
rm -rf ~/.electron-gyp
rm -rf ./node_modules


# install everything based on the package.json
npm install

# If when running you get a different node.js version error
# just like here: https://github.com/fyears/electron-python-example/issues/9
# then do the following as seen in SO: http://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron/42616189#42616189
./node_modules/.bin/electron-rebuild
```

**Comment by kascheri12** [comment]
Hmm, well I followed your instructions and got a different error:
```
Uncaught Error: Cannot find module 'zerorpc'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/ascherik/Git/kascheri12/rotkehlchen/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ascherik/Git/kascheri12/rotkehlchen/ui/zerorpc_client.js:1:172)
    at Object.<anonymous> (/Users/ascherik/Git/kascheri12/rotkehlchen/ui/zerorpc_client.js:9:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```


But then I wasn't able to get it again and I'm back to where I first started with the same error from the console that I had 3 comments ago and I can't seem to change it. I'm using `./setup.sh` to start the app.

**Comment by LefterisJP** [comment]
So you are trying to build from source? And have you installed all the dependencies as per the [guide](https://github.com/rotkehlchenio/rotkehlchen/blob/master/docs/source_install.md)? Your system seems to have trouble with installing the zerorpc dependency.

Question: When running the app from the downloaded binary it works?

**Comment by LefterisJP** [comment]
@kascheri12 So right now I tested it on my testing macbook air and it works. Made the following changes while building from source:

https://github.com/rotkehlchenio/rotkehlchen/commit/e4e013af26cf4cc0f889f53928015dd20532983e

So just do a normal npm install and then right after do the rebuilding, but specify python2 for the rebuild like this: ` PYTHON=/usr/bin/python2.7 ./node_modules/.bin/electron-rebuild`

Then you should be able to run it with `npm start`

**Comment by kascheri12** [comment]
Yes, I have followed the guide for OSX. I'm using virtualenv. 
Yes, when running from the downloaded binary it does work. v0.2.0 was stable.

Its still not working for me. I tried the new steps and I'm still getting this error in the console:
```
Uncaught Error: The module '~/rotkehlchen/node_modules/msgpack/build/Release/msgpackBinding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/rotkehlchen/node_modules/msgpack/lib/msgpack.js:6:14)
    at Object.<anonymous> (~/rotkehlchen/node_modules/msgpack/lib/msgpack.js:93:3)
```

**Comment by kascheri12** [comment]
To clarify, the build is successful every time now - the GUI pops up, but nothing happens. No login popup. The above error is in the console.

**Comment by LefterisJP** [comment]
If you get this error it means that the rebuild step of the setup guide did not work correctly. Do you have python2.7 also installed? Did you make sure to run the entire thing from scratch?

So something like:

```
rm -rf node_modules
rm -rf ~/.node-gyp
rm -rf ~/.electron-gyp
npm install
PYTHON=/usr/bin/python2.7 ./node_modules/.bin/electron-rebuild
```

and then doing `npm start`?

**Comment by chatzipan** [comment]
I followed your instructions, but i still keep getting this error when I do `npm start` and logs do not contain anything usefull.

<img width="1280" alt="screen shot 2018-05-22 at 23 38 01" src="https://user-images.githubusercontent.com/6288589/40864417-0989d6f2-65f4-11e8-8545-2188662b2dce.png">

**Comment by LefterisJP** [comment]
@chatzipan Can you run the python backend on its own? Are you inside a python virtualenv? Can you run `python -m rotkehlchen` and what does running it do?

**Comment by LefterisJP** [comment]
Good to hear @kascheri12. In the guide I have the proper combination of removing file and rebuilding modules that needs to be followed. I will try to improve this in the future if dependencies get simplified.
